encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>/", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("new/", views.new_page, name="new_page"),
    path("edit/<str:title>/", views.edit_page, name="edit_page"),
    path("delete/<str:title>/", views.delete_page, name="delete_page"),
    path("random/", views.random_entry, name="random_entry"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import markdown2
import random
import re

from django.shortcuts import redirect, render
from django.contrib import messages

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


# View function for displaying an encyclopedia entry
# If the requested entry does not exist, render an error page, otherwise render the entry page with the entry's content
def entry(request, title):
    entry = util.get_entry(title)
    if entry is None:
        # return HttpResponseRedirect()
        return render(
            request,
            "encyclopedia/error.html",
            {"message": "The requested page was not found."},
        )
    else:
        # Split the entry into title and body, and clean the title for display
        title, body = entry.split("\n", 1)
        clean_title = title.lstrip("# ").strip()
        # Convert the body from Markdown to HTML and render the entry page
        html_body = markdown2.markdown(body.strip())
        return render(
            request,
            "encyclopedia/entry.html",
            {
                "title": clean_title,
                "entry": html_body,
            },
        )


# View function for handling search requests
# If the search query matches an existing entry, redirect to that entry's page
# Otherwise, display a list of entries that contain the search query as a substring
def search(request):
    query = request.GET.get("q", "")
    entries = util.list_entries()

    for entry in entries:
        if entry.strip().lower() == query.lower():
            return redirect("encyclopedia:entry", title=entry)

    results = [entry for entry in entries if all(letter in entry.lower() for letter in query.lower())]
    print(f"Search query: '{query}' - Results: {results}")
    return render(
        request,
        "encyclopedia/search_results.html",
        {
            "query": query,
            "results": results,
        },
    )


# View function to allow users to create a new encyclopedia entry by entering a title, and content
# in a textarea
def new_page(request):
    if request.method == "POST":
        # Get the title and content from the form submission
        raw_title = request.POST.get("title").strip()
        title = raw_title.lstrip("# ").strip()

        content = request.POST.get("content", "")
        # Check if an entry with the same title already exists
        entries = util.list_entries()

        if title.lower() in (entry.lower() for entry in entries):
            return render(
                request,
                "encyclopedia/error.html",
                {"message": "An entry with this title already exists."},
            )
        else:
            # Save the new entry and redirect to its page
            util.save_entry(title, f"# {title}\n\n{content}")
            messages.success(request, f"{title} created successfully")
            return redirect("encyclopedia:entry", title=title)
    else:
        # If the request method is GET, render the new page form
        # Pre-fill title with `q` GET parameter when present (from search "Create" link)
        query = request.GET.get("q", "")
        return render(
            request,
            "encyclopedia/new_page.html",
            {
                "query": query,
            },
        )


# View function to allow users to edit an existing encyclopedia entry
def edit_page(request, title):
    entry = util.get_entry(title)
    # If the entry does not exist, render an error page
    if entry is None:
        return render(
            request,
            "encyclopedia/error.html",
            {"message": "The requested page was not found."},
        )

    linked_title, body = entry.split("\n", 1)
    clean_title = linked_title.lstrip("# ").strip()
    body = body.lstrip("\n")

    # If the request method is POST, save the edited content
    if request.method == "POST":
        # Get the updated content from the form submission
        content = request.POST.get("content", "")
        content = content.replace("\r\n", "\n")  # Normalize line endings
        content = content.strip()  # Remove leading/trailing whitespace
        content = re.sub(
            r"\n{3,}", "\n\n", content
        )  # Replace multiple newlines with one newlines

        # Save the updated entry and redirect to its page
        util.save_entry(clean_title, f"# {clean_title}\n\n{content}")

        # Redirect to the updated entry page
        messages.success(request, f"{clean_title} updated successfully")
        return redirect("encyclopedia:entry", title=clean_title)
    else:
        # If the request method is GET, render the edit page form with current content
        return render(
            request,
            "encyclopedia/edit_page.html",
            {
                "title": clean_title,
                "content": body,
            },
        )


# View function to delete an encyclopedia entry
def delete_page(request, title):
    entry = util.get_entry(title)
    if entry is None:
        return render(
            request,
            "encyclopedia/error.html",
            {"message": "The requested page was not found."},
        )

    # If the request is POST, delete the entry
    if request.method == "POST":
        util.delete_entry(title)

        # Add a success message and redirect to the index page
        messages.success(request, f"{title} deleted successfully")
        return redirect("encyclopedia:index")

    # Otherwise (GET), render confirmation page
    return render(
        request,
        "encyclopedia/delete_page.html",
        {
            "title": title,
        },
    )


# View function to display a random encyclopedia entry
def random_entry(request):
    entries = util.list_entries()
    random_title = random.choice(entries)
    return redirect("encyclopedia:entry", title=random_title)

encyclopedia/templates/encyclopedia/delete_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Delete {{ title }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete "{{ title }}"?</h1>
    <form action="{% url 'encyclopedia:delete_page' title=title %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Delete Page">
        <a class="btn btn-secondary" href="{% url 'encyclopedia:entry' title=title %}">Cancel</a>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ title }}
{% endblock %}

{% block body %}
    <h1>Editing {{ title }}...</h1>
    <form action="{% url 'encyclopedia:edit_page' title=title %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control" name="content" rows="5">{{ content }}</textarea>
        </div>
        <input type="submit" class="btn btn-primary" value="Save Changes">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <!-- Display the title of the entry and the content of the entry --->
    <h1>{{ title }}</h1>

    <p>{{ entry|safe }}</p>

    <!-- Link to edit the entry -->
    <a class="btn btn-primary" id="edit_page_button" href="{% url 'encyclopedia:edit_page' title=title %}">Edit Page</a>
    <a class="btn btn-danger" id="delete_page_button" href="{% url 'encyclopedia:delete_page' title=title %}">Delete Page</a>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error</h1>

    <p>{{ message }}</p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        <!-- Loop through entries and create a list item for each entry, linking to the entry page --->
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} mt-2" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}

                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    <h1>Create New Encyclopedia Entry</h1>
    <!-- Form for creating a new encyclopedia entry -->
    <form action="{% url 'encyclopedia:new_page' %}" method="post">
        {% csrf_token %}
        <label>Title:</label>
        <input class="form-control" type="text" name="title" value="{{ query }}" required>

        <label>Content (in Markdown):</label>
        <textarea class="form-control" name="content" rows="5" required></textarea><br>

        <input class="btn btn-primary" type="submit" value="Create Page">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results for "{{ query }}"
{% endblock %}

{% block body %}
    <h1>Showing {{ results|length }} results for "{{ query }}"</h1>

    <!-- Check if there are any search results -->
    {% if results %}
        <ul>
            <!-- Loop through search results and display them as links to their respective entries -->
            {% for entry in results %}
                <li><a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
    <!-- Display a message if no results were found -->
    <p>No results found for "{{ query }}".</p>
    <a class="btn btn-primary" href="{% url 'encyclopedia:new_page' %}?q={{ query|urlencode }}">Create "{{ query }}"?</a>
    {% endif %}

{% endblock %}